version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  macos-build-and-test:
    working_directory: ~/demo-react-native
    macos:
      xcode: 13.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test

    steps:
      - checkout
      - run: yarn install

      - run:
          command: pod install
          working_directory: ios

      - run:
          command: bundle install
          working_directory: ios

      - run:
          name: Fastlane
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
          working_directory: ios

      - store_artifacts:
          path: output

      - store_test_results:
          path: output/scan

workflows:
  node-android-ios:
    jobs:
      - macos-build-and-test
